=== sudoaugustin/supex/packages/schemas/config/0.0.1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Supex Configuration",
  "type": "object",
  "properties": {
    "$schema": true,
    "name": {
      "type": "string",
      "maxLength": 45
    },
    "author": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^[0-9]+(\\.[0-9]+){0,3}$"
    },
    "description": {
      "type": "string",
      "maxLength": 132
    },
    "commands": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "key": { "oneOf": [{ "type": "string" }, { "$ref": "#/definitions/Device" }] },
          "description": { "type": "string", "minLength": 10 }
        },
        "required": ["key", "description"],
        "additionalProperties": false
      }
    },
    "incognito": {
      "type": "string",
      "enum": ["spanning", "split", "not_allowed"],
      "default": "spanning"
    },
    "hosts": {
      "type": "array",
      "items": { "type": "string" }
    },
    "permissions": {
      "type": "object",
      "properties": {
        "required": { "type": "array", "items": { "type": "string" } },
        "optional": { "type": "array", "items": { "type": "string" } }
      }
    }
  },
  "required": ["name", "version", "description"],
  "additionalProperties": false,
  "definitions": {
    "Device": {
      "type": "object",
      "properties": {
        "mac": { "type": "string" },
        "linux": { "type": "string" },
        "default": { "type": "string" },
        "window": { "type": "string" },
        "chromeos": { "type": "string" }
      },
      "required": ["default"]
    }
  }
}

=== sudoaugustin/supex/apps/extension/supex.json
{
  "$schema": "/Users/augustin/Projects/supex/packages/schemas/config/0.0.1.json",
  "name": "Chromie",
  "author": "Augustin Joseph",
  "version": "0.0.0.2",
  "description": "Sharing not caring",
  "commands": {
    "hellwoorld": { "key": "Ctrl+R", "description": "hellwoorld" }
  },
  "hosts": ["*://developer.mozilla.org/*"],
  "incognito": "spanning",
  "permissions": {
    "required": ["declarativeNetRequest", "debugger"],
    "optional": ["alarms", "browserSettings", "contextualIdentities"]
  }
}
